--- #YAML:1.0
name:               Catalyst-Model-XML-Feed
version:            0.03
abstract:           Use RSS/Atom feeds as a Catalyst Model
author:
    - Jonathan Rockway <jrockway@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:             0
    Catalyst::Model:  0
    Class::Accessor:  0
    MRO::Compat:      0
    Test::More:       0
    URI:              0
    XML::Feed:        0.11
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
