# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Model-XML-Feed
version:      0.02
version_from: lib/Catalyst/Model/XML/Feed.pm
installdirs:  site
requires:
    Carp:                          0
    Catalyst::Model:               0
    Class::Accessor:               0
    NEXT:                          0
    Test::More:                    0
    URI:                           0
    XML::Feed:                     0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
